config/routes.rb
Rails.application.routes.draw do

  # This line mounts Spree's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Spree relies on it being the default of "spree"
  mount Spree::Core::Engine, :at => '/'
          # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  Spree::Core::Engine.routes.draw do
    resources :delivery,:about,:contact, only: [:index]
    
    
  end
  
end
   

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/spree/about_controller.rb
module Spree
    class Spree::AboutController < StoreController
        def index
        end
    end
end

app/controllers/spree/contact_controller.rb
module Spree
    class Spree::ContactController < StoreController
        def index
        end
    end
end

app/controllers/spree/delivery_controller.rb
module Spree
    class Spree::DeliveryController < StoreController
        def index
        end
    end
end

app/controllers/spree/taxon_controller_decorator.rb
module Spree
  class TaxonsController < Spree::StoreController
    rescue_from ActiveRecord::RecordNotFound, with: :render_404
    helper 'spree/products'

    respond_to :html

    def show
      @taxon = Spree::Taxon.where(permalink: params[:id]).first
      return unless @taxon

      @searcher = build_searcher(params.merge(taxon: @taxon.id, include_images: true))
      @products = @searcher.retrieve_products
      @taxonomies = Spree::Taxonomy.includes(root: :children)
    end

    private

    def accurate_title
      if @taxon
        @taxon.seo_title
      else
        super
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/spree/about_helper.rb
module Spree::AboutHelper
end

app/helpers/spree/base_helper_decorator.rb
#Modulul asta raspunde de logotip, logotipul poate fi schimbat in config!

module Spree::BaseHelper
    def logo(image_path = Spree::Config[:logo], img_options: {})
      link_to image_tag(image_path, img_options), spree.root_path
    end
end

#Breadcrumbs
def taxon_breadcrumbs_deco(taxon, separator = '', breadcrumb_class = 'breadcrumbs')
  return '' if current_page?('/') || taxon.nil?

  crumbs = [[Spree.t(:home), spree.root_path]]

  if taxon
    crumbs << [Spree.t(:products), products_path]
    crumbs += taxon.ancestors.collect { |a| [a.name, spree.nested_taxons_path(a.permalink)] } unless taxon.ancestors.empty?
    crumbs << [taxon.name, spree.nested_taxons_path(taxon.permalink)]
  else
    crumbs << [Spree.t(:products), products_path]
  end

  separator = raw(separator)

  items = crumbs.each_with_index.collect do |crumb, i|
    content_tag(:li, itemprop: 'itemListElement', itemscope: '', itemtype: 'https://schema.org/ListItem') do
      link_to(crumb.last, itemprop: 'item') do
        content_tag(:span, crumb.first, itemprop: 'name') + tag('meta', { itemprop: 'position', content: (i+1).to_s }, false, false)
      end + (crumb == crumbs.last ? '' : separator)
    end
  end
 content_tag(:div, content_tag(:div, content_tag(:div, content_tag(:div, content_tag(:ul, raw(items.map(&:mb_chars).join), itemscope: '', itemtype: 'https://schema.org/BreadcrumbList'), class: 'col-sm-12'), class: "row"), class: "container"), class: breadcrumb_class)
  
end



#Sidebar
def sidebar_tree(root_taxon, current_taxon, max_level = 1)
      return '' if max_level < 1 || root_taxon.children.empty?
      content_tag :li, class:'hidden' do
        taxons = root_taxon.children.map do |taxon|
          css_class = (current_taxon && current_taxon.self_and_ancestors.include?(taxon)) ? 'active' : nil
          content_tag :li, class: css_class do
           link_to(taxon.name, seo_url(taxon)) +
             sidebar_tree(taxon, current_taxon, max_level - 1)
          end
        end
        safe_join(taxons, "\n")
      end
end

app/helpers/spree/contact_helper.rb
module Spree::ContactHelper
end

app/helpers/spree/delivery_helper.rb
module Spree::DeliveryHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessangerApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/spree/about/index.html.erb
<div class="row">
    <div class="col-sm-7 vertical-align">
        <h2 class="title"><%= Spree.t(:about_us) %></h2>
        <% if I18n.locale == :ru %>
            <p><strong>Intex Dervelopment Co Ltd</strong> - мировой лидер по производству сборно-разборных бассейнов, надувных матрацев, лодок и предметов из ПВХ для семейного отдыха на воде, на даче и дома.
                <br/>
                    Миллионы людей используют продукцию Intex круглый год с удовольствием. Куда бы Вы не ехали, где бы Вы не отдыхали, товары Intex создадут прекрасную атмосферу для отдыха и принесут радость и веселье Вам и Вашей семье. 
                <br/><br/>
                    В квартире и на даче для детей доступны игровые комплексы, манежи, батуты, детские домики. На природе - бассейны, мячи, круги для плавания. Товары ИНТЕКС рекомендованы для дошкольного воспитания и обучения детей! Все изделия ИНТЕКС проходят длительные тесты на прочность, долговечность и экологичность. 
                    Каждый год выходит новая коллекция изделий ИНТЕКС.<br/> 
                    Вся продукция сертифицирована. 
                <br/><br/>
                    Качество, достойное самых изысканных требований!<br/> 
                    Превосходное соотношение цены и качества!<br/> 
                    INTEX - это не просто надувные игрушки, это среда обитания круглый год!
            </p>
        <% else %>
            <p><strong>Intex Dervelopment Co Ltd</strong> - мировой лидер по производству сборно-разборных бассейнов, надувных матрацев, лодок и предметов из ПВХ для семейного отдыха на воде, на даче и дома.
                <br/>
                    Миллионы людей используют продукцию Intex круглый год с удовольствием. Куда бы Вы не ехали, где бы Вы не отдыхали, товары Intex создадут прекрасную атмосферу для отдыха и принесут радость и веселье Вам и Вашей семье. 
                <br/><br/>
                    В квартире и на даче для детей доступны игровые комплексы, манежи, батуты, детские домики. На природе - бассейны, мячи, круги для плавания. Товары ИНТЕКС рекомендованы для дошкольного воспитания и обучения детей! Все изделия ИНТЕКС проходят длительные тесты на прочность, долговечность и экологичность. 
                    Каждый год выходит новая коллекция изделий ИНТЕКС.<br/> 
                    Вся продукция сертифицирована. 
                <br/><br/>
                    Качество, достойное самых изысканных требований!<br/> 
                    Превосходное соотношение цены и качества!<br/> 
                    INTEX - это не просто надувные игрушки, это среда обитания круглый год!
            </p>
        <% end %>
    </div><!-- end col -->
    <div class="col-sm-5 vertical-align">
        <figure class="zoom-in">
            <img src="https://www.intexcorp.com/media/heroimages/inflatable_spas_512x356-sep16.jpg" alt="">
        </figure>
    </div><!-- end col -->
</div>
<hr class="spacer-100">

app/views/spree/admin/translations/_form_fields.html.erb
<div id="attr_fields">
  <% SolidusI18n::Config.available_locales.each do |locale| %>
    <%= f.globalize_fields_for locale.to_sym do |g| %>
      <% @resource.class.translated_attribute_names.each_with_index do |attr, i| %>
        <div class="panel panel-default <%= attr %> <%= locale %>" style="display:<%= i == 0 ? 'auto' : 'none' %>;">
          <div class="panel-heading">
            <% I18n.with_locale(locale) do %>
              <%= @resource.class.human_attribute_name(attr) %>

              <div class="pull-right text-muted">
                <small><i><%= Spree.t(:'i18n.this_file_language') %></i></small>

                <% if locale.to_s.include?('-') %>
                  <img src="https://www.localeapp.com/assets/flags/regions/<%= locale.to_s.split('-').last %>.png">
                <% else %>
                  <img src="https://www.localeapp.com/assets/flags/languages/<%= locale %>.png">
                <% end %>
              </div>
            <% end %>
          </div>

          <div class="panel-body">
            <% if @resource.translations.columns_hash[attr.to_s].type == :text %>
              <%= g.text_area attr, class: 'form-control', rows: 4 %>
            <% else %>
              <%= g.text_field attr, class: 'form-control' %>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
  <% end %>

  <p class="no-translations" style="display: none">
    <%= Spree.t(:'globalize.no_translations_for_criteria') %>
  </p>
</div>

<hr/>

app/views/spree/contact/index.html.erb
            <div class="container" style="margin-top:-50px;">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="title-wrap">
                            <h2 class="title"><%= Spree.t(:contact_us) %></h2>
                            <h6 class="subtitle"><%= Spree.t(:foot_info) %></h6>
                        </div>
                    </div><!-- end col -->
                </div><!-- end row -->
                
                
                
                <div class="row">
                    <div class="col-sm-5">
                        <!--<h6 class="subtitle">Contact</h6>-->
                        <p><%= Spree.t(:contact_message) %></p>
                        <ul class="list alt-list">
                            <li><i class="fa fa-phone"></i> <b><%= Spree.t(:phone) %>:</b> +373 69 667 531 </li>
                            <li><i class="fa fa-phone"></i> <b><%= Spree.t(:phone) %>:</b> +373 78 495 757 </li>
                            <li><i class="fa fa-envelope"></i> <b>Email:</b> office@bazineintex.com</li>
                            <li><i class="fa fa-clock-o"></i> <b><%= Spree.t(:work_hours) %>:</b> 8:00 - 21:00, <%= Spree.t(:orar) %> </li>
                        </ul>
                        
                        <hr class="spacer-15">
                        
                        
                        
                    </div><!-- end col -->
                    <div class="col-sm-7">
                        <div class="panel-group accordion style1 hide" id="question" role="tablist" aria-multiselectable="true">
                            <div class="panel panel-default">
                                <div class="panel-heading" role="tab" id="questionOne">
                                    <h4 class="panel-title">
                                        <a class="collapsed" data-toggle="collapse" data-parent="#question" href="#collapseQuestionOne" aria-expanded="false" aria-controls="collapseOne">
                                            I have not received the refund by credit card after refund process completed.
                                        </a>
                                    </h4>
                                </div><!-- end panel-heading -->
                                <div id="collapseQuestionOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="questionOne" aria-expanded="false" style="height: 0px;">
                                    <div class="panel-body">
                                        <p>Lorem ipsum dolor sit amet, link adipisicing elit. Dicta voluptatem, tenetur eum tempore minus libero voluptates eos doloremque. Dolore minima rem consequuntur exercitationem quaerat deleniti repellendus enim necessitatibus mollitia tenetur?</p>
                                    </div><!-- end panel-body -->
                                </div><!-- end collapse -->
                            </div><!-- end panel -->

                            <div class="panel panel-default">
                                <div class="panel-heading" role="tab" id="questionTwo">
                                    <h4 class="panel-title">
                                        <a class="collapsed" data-toggle="collapse" data-parent="#question" href="#collapseQuestionTwo" aria-expanded="false" aria-controls="collapseTwo">
                                            I have questions about a product’s details
                                        </a>
                                    </h4>
                                </div><!-- end panel-heading -->
                                <div id="collapseQuestionTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="questionTwo" aria-expanded="false" style="height: 0px;">
                                    <div class="panel-body">
                                        <p>Lorem ipsum dolor sit amet, link adipisicing elit. Dicta voluptatem, tenetur eum tempore minus libero voluptates eos doloremque. Dolore minima rem consequuntur exercitationem quaerat deleniti repellendus enim necessitatibus mollitia tenetur?</p>
                                    </div><!-- end panel-body -->
                                </div><!-- end collapse -->
                            </div><!-- end panel -->

                            <div class="panel panel-default">
                                <div class="panel-heading" role="tab" id="questionThree">
                                    <h4 class="panel-title">
                                        <a class="collapsed" data-toggle="collapse" data-parent="#question" href="#collapseQuestionThree" aria-expanded="false" aria-controls="collapseThree">
                                            How do I get coupons or discounts?
                                        </a>
                                    </h4>
                                </div><!-- end panel-heading -->
                                <div id="collapseQuestionThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="questionThree" aria-expanded="false" style="height: 0px;">
                                    <div class="panel-body">
                                        <p>Lorem ipsum dolor sit amet, link adipisicing elit. Dicta voluptatem, tenetur eum tempore minus libero voluptates eos doloremque. Dolore minima rem consequuntur exercitationem quaerat deleniti repellendus enim necessitatibus mollitia tenetur?</p>
                                    </div><!-- end panel-body -->
                                </div><!-- end collapse -->
                            </div><!-- end panel -->
                            
                            <div class="panel panel-default">
                                <div class="panel-heading" role="tab" id="questionFour">
                                    <h4 class="panel-title">
                                        <a class="collapsed" data-toggle="collapse" data-parent="#question" href="#collapseQuestionFour" aria-expanded="false" aria-controls="collapseThree">
                                            How do I cancel an order?
                                        </a>
                                    </h4>
                                </div><!-- end panel-heading -->
                                <div id="collapseQuestionFour" class="panel-collapse collapse" role="tabpanel" aria-labelledby="questionFour" aria-expanded="false">
                                    <div class="panel-body">
                                        <p>Lorem ipsum dolor sit amet, link adipisicing elit. Dicta voluptatem, tenetur eum tempore minus libero voluptates eos doloremque. Dolore minima rem consequuntur exercitationem quaerat deleniti repellendus enim necessitatibus mollitia tenetur?</p>
                                    </div><!-- end panel-body -->
                                </div><!-- end collapse -->
                            </div><!-- end panel -->
                            
                            <div class="panel panel-default">
                                <div class="panel-heading" role="tab" id="questionFive">
                                    <h4 class="panel-title">
                                        <a class="collapsed" data-toggle="collapse" data-parent="#question" href="#collapseQuestionFive" aria-expanded="false" aria-controls="collapseThree">
                                            I haven’t received my order. What can I do?
                                        </a>
                                    </h4>
                                </div><!-- end panel-heading -->
                                <div id="collapseQuestionFive" class="panel-collapse collapse" role="tabpanel" aria-labelledby="questionFive" aria-expanded="false">
                                    <div class="panel-body">
                                        <p>Lorem ipsum dolor sit amet, link adipisicing elit. Dicta voluptatem, tenetur eum tempore minus libero voluptates eos doloremque. Dolore minima rem consequuntur exercitationem quaerat deleniti repellendus enim necessitatibus mollitia tenetur?</p>
                                    </div><!-- end panel-body -->
                                </div><!-- end collapse -->
                            </div><!-- end panel -->
                            
                            <div class="panel panel-default">
                                <div class="panel-heading" role="tab" id="questionSix">
                                    <h4 class="panel-title">
                                        <a class="collapsed" data-toggle="collapse" data-parent="#question" href="#collapseQuestionSix" aria-expanded="false" aria-controls="collapseThree">
                                            The product I received does not match the description. What can I do?
                                        </a>
                                    </h4>
                                </div><!-- end panel-heading -->
                                <div id="collapseQuestionSix" class="panel-collapse collapse" role="tabpanel" aria-labelledby="questionSix" aria-expanded="false">
                                    <div class="panel-body">
                                        <p>Lorem ipsum dolor sit amet, link adipisicing elit. Dicta voluptatem, tenetur eum tempore minus libero voluptates eos doloremque. Dolore minima rem consequuntur exercitationem quaerat deleniti repellendus enim necessitatibus mollitia tenetur?</p>
                                    </div><!-- end panel-body -->
                                </div><!-- end collapse -->
                            </div><!-- end panel -->
                        </div><!-- end panel-group -->
                    </div><!-- end col -->
                </div>
                
                <hr class="spacer-30 no-border">
                
                <div class="row column-4">
                    <div class="col-sm-4 col-md-4">
                        <div class="icon-boxes style1">
                            <div class="icon">
                                <i class="fa fa-truck text-dark"></i>
                            </div><!-- end icon -->
                            <div class="box-content">
                                <h6 class="alt-font text-uppercase"><%= Spree.t(:modal_livrare) %></h6>
                                <p><%= Spree.t(:contact_dela) %></p>
                            </div>
                        </div><!-- icon-box -->
                    </div><!-- end col -->
                    <div class="col-sm-4 col-md-4">
                        <div class="icon-boxes style1">
                            <div class="icon">
                                <i class="fa fa-gift text-dark"></i>
                            </div><!-- end icon -->
                            <div class="box-content">
                                <h6 class="alt-font text-uppercase"><%= Spree.t(:contact_cadou) %></h6>
                                <p><%= Spree.t(:contact_cadou_ms) %></p>
                            </div>
                        </div><!-- icon-box -->
                    </div><!-- end col -->
                    <div class="col-sm-4 col-md-4">
                        <div class="icon-boxes style1">
                            <div class="icon">
                                <i class="fa fa-credit-card text-dark"></i>
                            </div><!-- end icon -->
                            <div class="box-content">
                                <h6 class="alt-font text-uppercase"><%= Spree.t(:contact_plata) %></h6>
                                <p><%= Spree.t(:contact_plata_ms) %></p>
                            </div>
                        </div><!-- icon-box -->
                    </div><!-- end col -->
                </div><!-- end row -->
            </div><!-- end container -->    

app/views/spree/delivery/index.html.erb
<div class="container">
                <div class="row">
                    <div class="col-sm-12 text-left">
                        <h2 class="title">BazineINTEX предлагает услугу доставки товара по городу Кишинев и по Молдове.</h2>
                    </div><!-- end col -->    
                </div><!-- end row -->
                
                <hr class="spacer-5"> <hr class="spacer-20 no-border">
                
                <div class="row">
                    <div class="col-sm-12">
                        <h5 class="regular subtitle">Заказ оформляется:</h5>
                        <p>- по телефону</p>
                        
                        <hr class="spacer-30">
                        
                        <h5 class="regular subtitle">Доставка:</h5>
                        <p>- Доставка осуществляется в тот же день с момента заказа. Точное время доставки и адрес оговаривается с менеджером, после получения заказа.</p>
                        <p>- Стоимость доставки по Кишиневу - 30 лей. При заказе свыше 300 лей, доставка бесплатна .</p>
                        <p>- Стоимость доставки по стране расчитывается согласно тарифам Posta Moldovei.</p>
                        <p>- Вы имеете право отказаться от покупки товара, после его доставки. В этом случае Вам необходимо указать причину отказа и заплатить стоимость доставки, независимо от суммы заказа. Товар будет возвращен.</p>
                        
                        <hr class="spacer-15 no-border">
                        
                        <h6 class="regular subtitle">Оплата:</h6>
                        <ul class="list">
                            <li>Оплата производится наличным расчетом, по факту доставки товара.</li>
                        </ul>
                        
                        <hr class="spacer-30">
                        
                        <p class="regular subtitle">Если у Вас возникли вопросы, то наши менеджеры всегда готовы ответить на них. </p>
                        <h6 class="regular subtitle">Свяжитесь с нами, любым, удобным для Вас способом.</h6>
                        
                        <a href="/contact" class="btn btn-gray semi-circle btn-sm">Наши координаты</a>
                    </div><!-- end col -->
                </div><!-- end row -->                
            </div>

app/views/spree/home/index.html.erb
<% content_for :sidebar do %>
  <div data-hook="homepage_sidebar_navigation sexsex">
    <%= render :partial => 'spree/shared/taxonomies' %>
  </div>
<% end %>

<div data-hook="homepage_products">
  <% cache(cache_key_for_products) do %>
    <%= render :partial => 'spree/shared/products', :locals => { :products => @products } %>
  <% end %>
</div>

app/views/spree/layouts/spree_application.html.erb
<!doctype html>
<!--[if lt IE 7 ]> <html class="ie ie6" lang="<%= I18n.locale %>"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie ie7" lang="<%= I18n.locale %>"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie ie8" lang="<%= I18n.locale %>"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie ie9" lang="<%= I18n.locale %>"> <![endif]-->
<!--[if gt IE 9]><!--><html lang="<%= I18n.locale %>"><!--<![endif]-->
  <head data-hook="inside_head">
    <%= render :partial => '/spree/shared/head' %>
  </head>
  <body class="<%= body_class %>" id="<%= @body_id || 'default' %>" data-hook="body">
        
    <%= render :partial => '/spree/shared/header' %>
    <%= taxon_breadcrumbs_deco(@taxon) %> 
    <section class="<%= current_page?(root_path) ? "section light-backgorund" : "section white-backgorund" %>">
        <div class="container" >
            <div id="wrapper" class="row" data-hook>

                <%= render :partial => '/spree/shared/sidebar' if content_for? :sidebar %>
            
                <div  class="<%= !content_for?(:sidebar) ? "col-xs-12 col-sm-12 col-md-12" : "col-sm-8 col-md-9" %>" data-hook>
                    <%= flash_messages %>
                    <%= yield %>
                </div>
            
                <%= yield :templates %>
            
            </div>
        </div>
    </section>
    <%= render :partial => '/spree/shared/footer' %>
  </body>
</html>

app/views/spree/products/_image.html.erb
    <% if defined?(image) && image %>
      <%= image_tag image.attachment.url(:product), itemprop: "image", class:"aista" %>
    <% else %>
      <%#= image_tag @product.display_image.attachment(:product), itemprop: "image", class:"altu"%>
      <% @product.variant_images.each_with_index do |img, i| %>
      <div class="item <%= 'active' if i.zero? %>">
        <figure>
        <%= image_tag(img.attachment.url(:large)) %>
        </figure>
        </div>
      
    <% end %>
    <% end %>

app/views/spree/products/_promotions.html.erb
<% promotions = @product.possible_promotions %>
<% if promotions.any? %>
  <div id="promotions">
    <h3><%= Spree.t(:promotions) %></h3>
    <% promotions.each do |promotion| %>
    <div>
      <h4><%= promotion.name %></h4>
      <p><%= promotion.description %></p>
      <% if promotion.products.any? %>
      <ul>
        <% promotion.products.each do |product| %>
          <li><%= link_to product.name, product_path(product) %></li>
        <% end %>
      </ul>
      <% end %>
    </div>
    <% end %>
  </div>
<% end %>

app/views/spree/products/_taxons.html.erb
<% if !@product.taxons.blank? %>
  <div id="taxon-crumbs" data-hook class="alpha columns five omega">
    <h6 class="product-section-title"><%= Spree.t(:look_for_similar_items) %></h6>

    <div data-hook="product_taxons">
      <ul id="similar_items_by_taxon" data-hook>
      <% @product.taxons.each do |taxon| %>
        <li><%= link_to taxon.name, seo_url(taxon) %></li>
      <% end %>
      </ul>
    </div>

  </div>
<% end %>

app/views/spree/shared/_header.html.erb
<!--<header id="header" class="row" data-hook>
  <figure id="logo" class="columns six " data-hook><%#= logo img_options:{ class: 'img-responsive', width: '95' } %></figure>
          <%#= render :partial => 'spree/shared/main_nav_bar' if store_menu? %>
  <%#= render :partial => 'spree/shared/nav_bar' %>
</header> -->
<header>

<div class="topBar inverse">
    <div class="container">
        <ul class="list-inline pull-left">
            <li><span class="text-primary"><%= Spree.t(:header_call) %></span> <%= Spree.t(:header_call_call) %> +373 69 667 531</li>
        </ul>
         <%= render :partial => 'spree/shared/locale_selector' %> <!-- genereaza limbile in dreapta -->
    </div><!-- end container -->
</div><!-- end topBar -->

<div class="middleBar">
    <div class="container">
        <div class="row table">
            <div class="col-sm-3 vertical-align text-left hidden-xs">
                    <%= logo img_options:{ class: 'img-responsive', width: '200' } %>
            </div><!-- end col -->
            <%= render :partial => 'spree/shared/search' %>
        <!-- Bagam Social Media /facebook /instagram /odno... -->    
            <div class="col-sm-3 vertical-align header-items">
                        <div class="header-item mr-5 ">
                            <a href="https://www.facebook.com/intexmoldova/" target="_blank" data-toggle="tooltip" data-placement="top" title="" data-original-title="facebook">
                                <i class="fa fa-facebook"></i>
                                <!--<sub>2</sub> -->
                            </a>
                        </div>
                        <div class="header-item">
                            <a href="javascript:void(0);" data-toggle="tooltip"  target="_blank" data-placement="top" title="" data-original-title="instagram">
                                <i class="fa fa-instagram"></i>
                                <!--<sub>2</sub> -->
                            </a>
                        </div>
                        <div class="header-item">
                            <a href="https://www.ok.ru/profile/524154181477"  target="_blank" data-toggle="tooltip" data-placement="top" title="" data-original-title="instagram">
                                <i class="fa fa-odnoklassniki"></i>
                                <!--<sub>2</sub> -->
                            </a>
                        </div>
                    </div><!-- end col -->
        </div><!-- end  row -->
    </div><!-- end container -->
</div><!-- end middleBar -->
<!-- scriptu desemneaza sticky navBar -->
<script>
  $(document).ready(function(){
    $("#sticker").sticky({topSpacing:0});
  });
</script>
  <!-- start navbar -->
        <div id="sticker" class="navbar yamm navbar-default">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" data-toggle="collapse" data-target="#navbar-collapse-3" class="navbar-toggle">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    
                        <%= logo img_options:{ class: 'navbar-brand visible-xs ', width: '100' } %>
                    
                </div>
                <div id="navbar-collapse-3" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<%= root_path %>"><%= Spree.t(:home) %></a></li>
                        <li><%= link_to Spree.t(:about_us), about_index_path %></li>
                        <li><%= link_to Spree.t(:contact_us), contact_index_path %></li>
                        <li><%= link_to Spree.t(:delivery), delivery_index_path %></li>
                    </ul><!-- end navbar-nav -->
                </div><!-- end navbar collapse -->
            </div><!-- end container -->
        </div><!-- end navbar -->
</header>
        

app/views/spree/shared/_nav_bar.html.erb
<nav id="top-nav-bar" class="columns ten">
  <ul id="nav-bar" class="inline" data-hook>
    <li id="search-bar" data-hook>
      <%= render :partial => 'spree/shared/search' %>
    </li>
  </ul>
</nav>

app/views/spree/shared/_sidebar.html.erb
<div class="col-sm-4 col-md-3">
<aside id="sidebar" class="columns four" data-hook>
  <%= yield :sidebar %>
</aside>
</div>